import { Metadata } from 'next'
import './globals.sass'
import { Inter,  } from 'next/font/google'
import TemporaryDrawer from '@/components/Header/Header'
import { Footer } from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Main messenger page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <TemporaryDrawer/>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
